// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: '41050657476',
    projectId: 'mr-plando',
    authDomain: 'mr-plando.firebaseapp.com',
    storageBucket: 'mr-plando.appspot.com',
    measurementId: 'YOUR_MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDry3qI45RFcHS7bYOAaLhg6DSSVokXD2E', // Firebase Console에서 Android 구성 파일에서 확인
    appId: '1:41050657476:android:e1d2a296d565f6656eef91',
    messagingSenderId: '41050657476',
    projectId: 'mr-plando',
    storageBucket: 'mr-plando.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFnWii_sq0sBmKayuiQyxAvbw4lPbYYwo', // Firebase Console에서 iOS 구성 파일에서 확인
    appId: '1:41050657476:ios:1014aea6d70fc3d96eef91',
    messagingSenderId: '41050657476',
    projectId: 'mr-plando',
    storageBucket: 'mr-plando.appspot.com',
    iosBundleId: 'com.huiriric.mrplando',
  );
}
